### ISSUE TITLE
String

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/berkay_ergun_splash_onboard_login#1]
Burdaki stringleri ya syafa basında çekelim ya da string sınıfnda çeklim
https://github.com/VBT-FlutterCamp/berkay_ergun_splash_onboard_login/blob/bb105db2dff9b397c7a9e3f76c2997196655e7aa/splash_onboard/lib/products/widgets/custom_text_form_field.dart#L43

**Comment by Krdnzbyza** [comment]
ilerde 6 yerine 4 ten küçük olamaz denilirse degiştirlmesi kolay olamlı

**Comment by xbergun** [comment]
Düzeltildi, teşekkürler.
