### ISSUE TITLE
Elevation

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/berkay_ergun_splash_onboard_login#2]
Elevation default degeri degiştiriyor mu şu an sayfada ? Saya bsında double _elevationDoubleValue = 1;  şeklinde tanımlayıp çekmeliyiz  https://github.com/VBT-FlutterCamp/berkay_ergun_splash_onboard_login/blob/bb105db2dff9b397c7a9e3f76c2997196655e7aa/splash_onboard/lib/feature/login/view/login_page_body.dart#L64

**Comment by xbergun** [comment]
Düzeltildi, teşekkürler.
